### ISSUE TITLE
Configurable message format.

### ISSUE THREAD

**Issue by luqasz** [ClearcodeHQ/Go-Forward#16]
As syslog messages are sent / forwarded with different fields and formats, config option providing message format is essential.
Assumptions:
* message format is known
* program is only interested in user defined fields
* fields are parsed

This may be implemented using [parser](https://golang.org/pkg/text/template/parse/).

**Comment by luqasz** [comment]
I was thinking about this and this may be a good feature but not for now. As stated in [RFC](https://tools.ietf.org/html/rfc3164), time format is fixed. I think that implementing pure RFC will be fine.

@mmaslowskicc what do you think ?

**Comment by mmaslowskicc** [comment]
Maybe implement the pure RFC and wait until we find a use case for a different log format? E.g. when some specific syslog implementation sends messsages in a different format, or if we add a non-syslog source.

**Comment by luqasz** [comment]
Closed in c9327c618b5e9ace49576cf414cb017f22c73b22
