### ISSUE TITLE
One uploader at a time.

### ISSUE THREAD

**Issue by luqasz** [ClearcodeHQ/Go-Forward#2]
Cloudwatch logs have certain constraints for `putLogEvents` action:
* 200ms delay between `putLogEventsDelay` call.
* `sequenceToken` must change in order to successfully send messages. Otherwise `DataAlreadyAcceptedException` is returned as an error.
* `sequenceToken` is assigned for each log stream.

**Problem**:
How to run a goroutine and know when it finished ?

**Comment by luqasz** [comment]
@mmaslowskicc 
@jotes 
Maybe you can help ?

**Comment by mmaslowskicc** [comment]
This needs either using a channel to synchronize the goroutines (https://github.com/ClearcodeHQ/Go-Forward/pull/4) or using a single goroutine for the sequential operations. I need to check the whole code if the single goroutine for sending approach could work.

**Comment by luqasz** [comment]
I've found the solution [here](https://blog.golang.org/advanced-go-concurrency-patterns) and it's [code](https://github.com/golang/talks/tree/master/2013/advconc).
