### ISSUE TITLE
Include a copy of GNU GPL version 3

### ISSUE THREAD

**Issue by mmaslowskicc** [ClearcodeHQ/Go-Forward#9]
I don't see where we specify that the LGPL applies, but we should include the GPL too: LGPL3 works as an additional permission and refers to the GPL. See <https://www.gnu.org/licenses/gpl-howto.en.html>.

**Comment by luqasz** [comment]
It is in `https://github.com/ClearcodeHQ/Go-Forward/blob/master/LICENSE`

**Comment by mmaslowskicc** [comment]
It's LGPL. We need both, e.g. since including the text of the GPL itself is needed for distribution of unmodified source copies.

**Comment by luqasz** [comment]
Done in e77b403084bf318bb03300412082dafa8e9b2935
